name: CI - lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 22
      uses: actions/setup-node@v1
      with:
        node-version: 22
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
