name: CI - test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 22
      uses: actions/setup-node@v1
      with:
        node-version: 22
    - name: Install dependencies
      run: npm ci
    - name: Build library
      run: npm run build
    - name: Test
      run: npm test
